version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - misspell
    - unconvert
    - unused
    - gosec

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
