apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: staging
data:
  APP_PORT: "8080"
  APP_ENV: "staging"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "auth"
  DB_SSLMODE: "disable"
  JWT_ACCESS_TTL: "15m"
  JWT_REFRESH_TTL: "168h"
  BRUTE_FORCE_MAX_ATTEMPTS: "5"
  BRUTE_FORCE_WINDOW: "15m"
  LOG_LEVEL: "info"
